server:
  port: 8081

person:
  lastName: zhangsan
  age: 18
  boss: false
  birth: 2020/1/2
  maps: {k1: v1, k2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 2


spring:
  profiles:
    active: prod
---
server:
  port: 8088
spring:
  profiles: dev
---
server:
  port: 8089

spring:
  profiles: prod
